# Generated by Django 3.2.14 on 2022-08-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nickelpure', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
